### ISSUE TITLE
Failed to decrypt files

### ISSUE THREAD

**Issue by J1vdL** [anojht/synology-cloud-sync-decrypt-tool#1]
I've installed the new (June) release to decrypt synology cloud sync files in OSX13.6. No problems installing but keep getting the the message 'failed to decrypt files' after supplying private and public key. Any suggestions? Thanks already!

**Comment by anojht** [comment]
Can you post the logs output by the application, they can be found in the following directory: `~/Library/Logs/com.anojht.opensourcesynologycloudsyncdecrypttool.log`

**Comment by J1vdL** [comment]
Thanks for your reply. This is from the error log
2018-09-05 11:10:38,289 INFO syndecrypt.files decrypting
"/Users/j/Desktop/filefromsynccloud1.pdf" to
"/Users/jDesktop/Output/filefromsynccloud1.pdf"
2018-09-05 11:10:38,513 ERROR syndecrypt.files decryption failed, exception
occurred: <class 'FileNotFoundError'>: [Errno 2] No such file or directory:
'/usr/local/bin/lz4': '/usr/local/bin/lz4'
2018-09-05 11:10:38,513 ERROR synology_logger [Errno 2] No such file or
directory: '/usr/local/bin/lz4': '/usr/local/bin/lz4'

**Comment by anojht** [comment]
Ah the reason the files are not decrypting is because the LZ4 dependency was not installed. Could you please completely close the app down and relaunch it? The app is set to install the dependencies if it does not detect them in your system. In some cases a restart of your mac before launching the program is needed.

**Comment by J1vdL** [comment]
I tried completely closing, relaunching, restarting mac and re-installing. I didn't get a pop-up or the like to install dependencies. Can I install this dependency separately? Thanks.

**Comment by anojht** [comment]
That's odd, could your right click the app and click Show Package Contents then click Contents then click Resources. You will see a script called InstallMeFirst, double click to run it. It may prompt for passwords and asking for permissions to run, this is because it will install LZ4 as well as Xcode tools from Apple so that it can run. Let me know if you run into issues!

**Comment by J1vdL** [comment]
I had to install Xcode separately. Afterwards I was able to successfully run InstallMeFirst. Decryption now works. Thanks for your help.

**Comment by anojht** [comment]
I am glad it works now! If you are happy with the program please give this repository a star!
